version: "3.9"

services:
  backend:
    build:
      context: . # tells docker compose to start building from my project root
      dockerfile: src/Dockerfile # correct directory for the Dockerfile
    ports:
      - "8000:8000"
    env_file: # Automatically loads my .env file
      - .env
    restart: unless-stopped
